Repository GSM-MSG/SMS-BackEnd, pull requests merged in 2023-11, with the labels that each got.

#250 🔀 250 :: Redis TTL 적용 오류 수정
  sms-persistence/src/main/kotlin/team/msg/sms/global/config/RedisConfig.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#252 🔨 cd 작동조건 master로 변경
  .github/workflows/sms_backend_cd.yml
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🌏 Deploy

#254 🔨 master branch CD 파일이름 변경
  .github/workflows/sms_backend_master_cd.yml
Labels: 2️⃣ Priority: Medium, ⚡️ Simple, 🌏 Deploy

#258 🔀 :: 255 - develop branch cd 추가
  .github/workflows/sms_backend_develop_cd.yml
Labels: 1️⃣ Priority: High, 🌏 Deploy
