Repository GSM-MSG/SMS-BackEnd, pull requests merged in 2023-08, with the labels that each got.

#174 🔀 :: 173 - 학생에서 드림북 정보 삭제
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/model/Student.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/mapper/StudentMapper.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#175 🔀 :: studentTechStack -> techStack으로 변경
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#179 🔀 :: 178 - 정보기입 부분 리팩토링 및 500 해결
  sms-core/src/main/kotlin/team/msg/sms/domain/certificate/service/CommandCertificateService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/certificate/service/impl/CommandCertificateServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/certificate/spi/CommandCertificatePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/service/CommandLanguageCertificateService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/service/impl/CommandLanguageCertificateServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/languagecertificate/spi/CommandLanguageCertificatePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/prize/service/PrizeService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/region/service/CommandRegionService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/region/service/impl/CommandRegionServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/region/spi/CommandRegionPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/certificate/CertificatePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/ImagePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/languagecertificate/LanguageCertificatePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/prize/PrizePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/ProjectLinkPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/region/RegionPersistenceAdapter.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#181 🔀 :: 180 - 디테일 페이지에 상과 프로젝트 추가
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoAnonymousUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoDetailUseCase.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoAnonymousWebResponse.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoWebResponse.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/MainStudentsWebResponse.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#182 🔀 :: 테크 스택 네이밍 수정
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#185 🔀 :: 전부 다 techStacks 로 변경
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/MainStudentsResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/techstack/dto/res/TechStacksResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/techstack/usecase/QueryAllTechStackUseCase.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/techstack/TechStackWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/techstack/dto/res/TechStacksWebResponse.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#186 🔀 :: @Repository 어노테이션 추가
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/image/repository/ImageJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/prize/repository/PrizeJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectLinkJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/project/repository/ProjectTechStackJpaRepository.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#188 🔀 :: 프로젝트 디테일 페이지에 icon 값 추가
  sms-core/src/main/kotlin/team/msg/sms/common/util/ProjectUtil.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/project/dto/res/ProjectResponseData.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#190 🔀 :: 189 - 현재 DTO 네이밍 일치
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/SignUpWebRequest.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#192 🔀 :: 191 - 쿠키랑 토큰 중복처리
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/CookieJwtFilter.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/auth/AuthWebAdapter.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#194 🔀 :: 193 - JWT 필터 부분 UseCase 로 변경
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ExistStudentUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryUserByUserIdUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/FilterConfig.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/filter/JwtFilter.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#198 🔀 :: 필터 빈 리스트 보낼때 반환 안되는 이슈 해결
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/FilterStudentServiceImpl.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#207 🔀 :: 프로젝트 링크 반환 id값 제거
  sms-core/src/main/kotlin/team/msg/sms/common/util/ProjectUtil.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/project/dto/res/ProjectLinkResponseData.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#219 🔀 :: appspec 업데이트
  appspec.yml
Labels: 🌏 Deploy

#220 🔀 :: appspec.yml 변경
  appspec.yml
  scripts/shell_start.sh
Labels: 🌏 Deploy

#215 🔀 :: Query -> Get으로 변경
  sms-core/src/main/kotlin/team/msg/sms/domain/major/service/impl/GetMajorServiceImpl.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple
