Repository GSM-MSG/SMS-BackEnd, pull requests merged in 2024-06, with the labels that each got.

#339 포트폴리오 옵셔널처리
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoRequestData.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/ModifyStudentInfoWebRequest.kt
Labels: 0️⃣ Priority: Critical

#343 기업이 조회할 수 있는 링크를 생성할 때 발생하는 500 예외를 고쳤습니다.
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#346 학생 리스트 조회 시 캐시 문제 해결
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#347 develop 변경사항을 master에 머지합니다!
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/FindAllUseCase.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#352 student 학번 null인 계정 0으로 저장되도록 변경
  sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#357 학과 결정 조건을 변경하였습니다.
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/SignUpUseCase.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#359 인증제 폼 생성 기능 개발
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationAreaFormRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationFormRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationSectionRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationForm.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationSection.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationFormService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationSectionService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandAuthenticationFormService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandAuthenticationSectionService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandGroupAuthenticationAreaService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandSelectorSectionValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GroupAuthenticationAreaService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/SelectorSectionValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandAuthenticationFormServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandAuthenticationSectionServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandGroupAuthenticationAreaServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandSelectorSectionValueServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationFormPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationSectionPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandAuthenticationFormPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandAuthenticationSectionPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandGroupAuthenticationAreaPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandSelectorSectionValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/GroupAuthenticationAreaPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/SelectorSectionValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/CreateAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/GetTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/GetTeacherServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryTeacherPort.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationFormPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationSectionPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/GroupAuthenticationAreaPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/SelectorSectionValuePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationFormJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationSectionJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationFormMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationSectionJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/HomeroomTeacherPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/TeacherPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/TeacherJpaRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationFormWebRequest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#364 인증제 DTO 수정 및 변경사항 UseCase에 적용
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitUserFormRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationAreaFormResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionFieldResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationFormResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitAuthenticationWebRequest.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationFormWebResponse.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 📝 Docs

#363 포트폴리오 PDF 업로드 기능 개발
  sms-core/src/main/kotlin/team/msg/sms/common/util/FileUtil.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/file/spi/UploadFilePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/PortfolioInvalidExtensionException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/error/StudentErrorCode.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/model/Student.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentPortfolioFileUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/thirdparty/aws/stroage/AwsS3Adapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/mapper/StudentMapper.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#368 포트폴리오 PDF 파일 관련 DTO 수정 및 "학생정보 수정 로직" 수정
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentInfoUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTokenUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenWebResponse.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/UserWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/user/dto/res/UserProfileDetailWebResponse.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#369 어색한 네임들 다 수정
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationFieldRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationSectionRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitUserFormRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionFieldResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationField.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/FieldType.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/UserFormValue.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/CreateAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationFieldJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationSectionJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/UserFormValueJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/UserFormValueMapper.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#373 :recycle: /student/pdf 경로 접근 권한 추가
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#374 FieldGroup 추가
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationFieldGroupRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/CreateAuthenticationSectionRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/SubmitUserFormRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationFieldGroupResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/AuthenticationSectionResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationField.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/AuthenticationFieldGroup.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/UserFormValue.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/AuthenticationFieldGroupService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandAuthenticationFieldGroupService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationFieldGroupService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetAuthenticationFieldService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandAuthenticationFieldGroupServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationFieldGroupServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationFieldServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/AuthenticationFieldGroupPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandAuthenticationFieldGroupPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationFieldGroupPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationFieldPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/CreateAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationAreaPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationFieldGroupPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationFieldPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/SelectorSectionValuePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationFieldGroupJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/AuthenticationFieldJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/UserFormValueJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationFieldGroupMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/AuthenticationFieldMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/UserFormValueMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationAreaJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationFieldGroupJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationFieldJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/SelectorSectionValueJpaRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#379 🔀 확장명을 포함해서 저장하기
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/ModifyStudentPortfolioFileUseCase.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor
