Repository GSM-MSG/SMS-BackEnd, pull requests merged in 2024-05, with the labels that each got.

#310 로그인 시 GAuth 학번과 다르면 업데이트
  sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CommandUserService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CommandUserServiceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#312 master에 develop 변경사항 반영
  sms-core/src/main/kotlin/team/msg/sms/domain/auth/model/Role.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/SignInUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/auth/usecase/VerifyAccessUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/dto/req/SignUpHomeroomTeacherRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/HomeroomTeacherAlreadyException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/TeacherAlreadyException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/exception/error/TeacherErrorCode.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/model/HomeroomTeacher.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/model/Teacher.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CheckHomeroomTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CheckTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandHomeroomTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/CommandTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/HomeroomTeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/TeacherService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CheckHomeroomTeacherServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CheckTeacherServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandHomeroomTeacherServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/service/impl/CommandTeacherServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/CommandHomeroomTeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/CommandTeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/HomeroomTeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryHomeroomTeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/QueryTeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/spi/TeacherPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpDeputyPrincipalTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpDirectorTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpHomeroomTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpPrincipalTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/teacher/usecase/SignUpTeacherUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CheckUserService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/CommandUserService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CheckUserServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/user/service/impl/CommandUserServiceImpl.kt
  sms-core/src/test/kotlin/team/msg/sms/domain/auth/core/usecase/GAuthSignInUseCaseTest.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/HomeroomTeacherPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/TeacherPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/entity/HomeroomTeacherJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/entity/TeacherJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/mapper/HomeroomTeacherMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/mapper/TeacherMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/HomeroomTeacherJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/teacher/repository/TeacherJpaRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/TeacherWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/teacher/dto/req/SignUpHomeroomTeacherWebRequest.kt
Labels: 1️⃣ Priority: High, 🌏 Deploy

#314 학생정보 조회 링크 생성 API 개발
  sms-core/src/main/kotlin/team/msg/sms/common/util/PasswordUtil.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/CreateStudentLinkResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/model/StudentLink.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CheckStudentLinkService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/CommandStudentLinkService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/StudentLinkService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CheckStudentLinkServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/CommandStudentLinkServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/CommandStudentLinkPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentLinkPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/StudentLinkPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/CreateStudentLinkUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentLinkPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/entity/StudentLinkEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/mapper/StudentLinkMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentLinkRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/CreateStudentLinkWebResponse.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#318 token 링크를 클릭하면 기업이 학생 정보를 볼 수 있도록 API를 작성했습니다.
  sms-core/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/StudentLinkNotFoundException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/exception/error/StudentErrorCode.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/GetStudentLinkService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/StudentLinkService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/service/impl/GetStudentLinkServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/spi/QueryStudentLinkPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/student/usecase/StudentInfoTokenUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/StudentLinkPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/student/repository/StudentLinkRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTokenWebResponse.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#317 🔁 링크 최소 최대 만료기간 지정
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/req/CreateStudentLinkWebRequest.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor
