Repository GSM-MSG/SMS-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#381 🔀 학생정보 수정 API 접근 권한 추가
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#384 🔀 추가되지 않은 portfolioFileUrl 추가하기
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/StudentWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/student/dto/res/DetailStudentInfoTeacherWebResponse.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#382 학생이 제출한 폼 상세 조회 기능 개발
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/StudentAuthenticationFormResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/MarkingBoardNotFoundException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/UserFormValue.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingBoardService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetUserFormValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetAuthenticationSectionServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingBoardServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetUserFormValueServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryAuthenticationSectionPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingBoardPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryUserFormValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryStudentAuthenticationFormDetailUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationSectionPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingBoardPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/UserFormValuePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/UserFormValueJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/UserFormValueRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryStudentFormDetailWebResponse.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#387 선생님 학생 채점 기능 개발
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/GradingRequestData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/UserFormValueNotFoundException.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/exception/error/AuthenticationErrorCode.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/MarkingValue.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CheckUserFormValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/CommandMarkingValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/MarkingValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/UserFormValueService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CheckUserFormValueServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/CommandMarkingServiceValueImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingValueServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/CommandMarkingValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/MarkingValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryUserFormValuePort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/GradingAuthenticationFormUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingValuePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/UserFormValuePersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/MarkingValueJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/MarkingValueMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/MarkingValueJpaRepository.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/req/GradingRequest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#391 section과 field를 조회할때 sort 컬럼을 오름차순 정렬 합니다
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/AuthenticationFieldPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/AuthenticationFieldJpaRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/AuthenticationSectionRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#396 학생 폼 제출할 때 재 활용성을 올립니다.
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#400 학생 인증제의 상태를 조회하는 API 개발
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationVerifyResponseData.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/model/MarkingBoard.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/GetMarkingBoardService.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/service/impl/GetMarkingBoardServiceImpl.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/spi/QueryMarkingBoardPort.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/GradingAuthenticationFormUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/QueryAuthenticationVerifyUseCase.kt
  sms-core/src/main/kotlin/team/msg/sms/domain/authentication/usecase/SubmitUserFormDataUseCase.kt
  sms-infrastructure/src/main/kotlin/team/msg/sms/global/security/SecurityConfig.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/MarkingBoardPersistenceAdapter.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/entity/MarkingBoardJpaEntity.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/mapper/MarkingBoardMapper.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/MarkingBoardCustomRepository.kt
  sms-persistence/src/main/kotlin/team/msg/sms/persistence/authentication/repository/queryDSL/MarkingBoardRepositoryImpl.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/AuthenticationWebAdapter.kt
  sms-presentation/src/main/kotlin/team/msg/sms/domain/authentication/dto/res/QueryAuthenticationVerifyWebResponse.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#407 🔁 포트폴리오 URL이 비어있는 상황에서는 무조건 빈 문자열을 반환함
  sms-core/src/main/kotlin/team/msg/sms/domain/user/usecase/QueryCurrentUserProfileDetailUseCase.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor
